version: '3.9'

services:
  # Backend services
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      FLASK_APP: __init__.py
    depends_on:
      - db
    networks:
      - asset_management_network

  db:
    image: postgres:13
    container_name: asset_management_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - asset_management_network

  # Frontend service
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - asset_management_network

networks:
  asset_management_network:
    driver: bridge

volumes:
  db_data:
